# Generated by Django 6.0.6 on 2026-06-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_birth', models.IntegerField()),
                ('is_healthy', models.BooleanField(default=True)),
            ],
        ),
    ]
